### ISSUE TITLE
Permitir o cadastro de apenas um quarto por número

### ISSUE THREAD

**Issue by Fgarm** [RenanGAS/SGH#3]
Como descrito no título, isso é por causa do Requisito funcional 8 do cadastro de apartamentos do documento de requisitos.
Provavelmente da pra fzr isso com uma mudança no quartos.cpp, mas ele vai ter que checar todos os outros quartos pra ver se já n tem um com o nome, então tem que ver se vamos arrumar ou se marca como wontfix

**Comment by Fgarm** [comment]
Caso o segundo, provavelmente tem que tirar esse req funcional, mas n sei se isso da problema

**Comment by RenanGAS** [comment]
Wontfix parece uma boa!
